# Generated by Django 3.2.6 on 2021-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.jpeg', upload_to='uploads/profile_pictures'),
        ),
    ]
