# Generated by Django 3.2.6 on 2021-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='media/uploads/profile_pictures/default.jpg', upload_to='media/uploads/profile_pictures'),
        ),
    ]
