# Generated by Django 3.2.9 on 2022-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_registrarcomment_registrarpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarpost',
            old_name='comment',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='registrarpost',
            name='post',
        ),
        migrations.AddField(
            model_name='registrarpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
