# Generated by Django 3.2.9 on 2022-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_announcement_announcementpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
    ]
