# Generated by Django 3.2.9 on 2022-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
