# Generated by Django 3.2.9 on 2022-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20220518_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultypost',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='faculty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/profile_pictures'),
        ),
        migrations.DeleteModel(
            name='AnnouncementPost',
        ),
        migrations.DeleteModel(
            name='FacultyPost',
        ),
    ]
