# Generated by Django 3.2.9 on 2022-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_chairperson',
            field=models.BooleanField(default=False, verbose_name='is_chairperson'),
        ),
    ]
